# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7eedc0ad45c4ddfccf916655a8ff8bcf8db614861edcaceadf5c8b3c817d6ef04430713e886f0acccf937e0c35a5dc1ea14928dcc7abf11f3fc5392478f017d

test:
  secret_key_base: 1e2fd1f6ab660308f607efca7357b5603f267c6eb679001cabe9401ae4ffe4f1be6577fa03b5f6663cab0763cdfe7dd671c43ce2c314afdbe4072114d6530904

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
